### ISSUE TITLE
Query as anonymous

### ISSUE THREAD

**Issue by NgKhacDuy** [Riktam-Santra/mangadex_library#6]
Im using your lib, but the version is before 2.0.0, i saw u updated version to 2.0.5, but seem like you are require user to login to query
Is there any way to query without auth

**Comment by Riktam-Santra** [comment]
Unfortunately there is not support for anonymous queries right now, but I'm planning on putting the functionality by this week.

If you still need a work around, you can still use the MangadexClient  rather than the new PersonalClient, just use the `setToken()` function of the MangadexClient to set the Token to null.

 The refresh timer is ignored for MangadexClient when the token is null so it won't call the refresh endpoint at all.
